import openai
import json
import os
import pickle
import uuid
# from zhipuai import ZhipuAI
from pdb import set_trace as bp

# client = ZhipuAI(api_key="880f73cd7d98f9981b1b8a80dd1136c6.L4mk4JObnqYJ7USZ")
from openai import OpenAI
client = OpenAI(api_key = 'sk-7hyJmJEhn2MYBPlR16C6163b4a3546A8A021D1413c6416B3', base_url = 'https://api.yxflow.xyz/v1')
CACHE_FILE = os.environ.get('GEO_CACHE_FILE', 'geo_optimizations_cache.json')

COMMON_SYSTEM_PROMPT = """You are an expert ml researcher having previous background in SEO and search engines in general. You are working on novel research ideas for next generation of products. These products will have language models augmented with search engines, with the task of answering questions based on sources backed by the search engine. This new set of systems will be collectively called language engines (generative search engines). This will require websites to update their SEO techniques to rank higher in the llm generated answer. Specifically they will use GEO (Generative Engine Optimization) techniques to boost their visibility in the final text answer outputted by the Language Engine.  
"""

COMMON_USER_PROMPT_START = "General Instruction: I will give you a source of website source. The source along with other sources. will be used for answering some question posed by the user. The answer will be generated by LLM using these multiple sources, and each of the lines will be cited by Language model. As the owner of the source, the task is to increase your visibility in the answer. To do this you will appropriately change the text of the source (without changing the content) so that it is ranked higher in terms of impact in the final answer.\n\n"

global_cache = None
def call_gpt(user_prompt, system_prompt = COMMON_SYSTEM_PROMPT, model = 'gpt-3.5-turbo-16k', temperature = 0.0, num_completions = 1, regenerte_answer = False, pre_msgs = None):
    global global_cache
    # model = "GLM-3-Turbo"
    cache_file = CACHE_FILE.replace('.json',f'_{model}.json')
    if os.environ.get('STATIC_CACHE', None) == 'True':
        if global_cache is None:
            global_cache = json.load(open(cache_file, 'r'))
        cache = global_cache
    else:
        cache = json.load(open(cache_file, 'r'))
    if str((user_prompt, system_prompt)) in cache and not regenerte_answer:
        return cache[str((user_prompt, system_prompt))][-1]

    # print('Cache Miss')

    messages = [
        { 'role': "system", 'content': system_prompt },
        { 'role': "user", 'content': user_prompt }
    ]

    if pre_msgs is not None:
        messages = [messages[0]] + pre_msgs + messages[1:]

    for attempt in range(10):
        try:
            responses = client.chat.completions.create(
            # responses = openai.ChatCompletion.create(
                model = model,
                # model = "GLM-3-Turbo", 
                temperature=temperature,
                max_tokens=3192,
                messages = messages,
                top_p=1,
                n=num_completions,
            )
            break
        except Exception as e:
            print('Error',e)
            print(str(e).find('maximum context length'))
            if str(e).find('maximum context length')!=-1:
                try:
                    a = str(e).find('messages resulted in ') + len('messages resulted in ')
                    b = str(e).find(' tokens', a)
                    num_tokens_excess = 2000 / int(str(e)[a:b])
                except:
                    a = str(e).find('you requested ') + len('you requested ')
                    b = str(e).find(' tokens', a)
                    num_tokens_excess = 2000 / int(str(e)[a:b])
                    
                print(num_tokens_excess)
                lup = len(messages[-1]['content'])
                messages[-1]['content'] = messages[-1]['content'][:int(lup * num_tokens_excess)]  
            if attempt > 5:
                messages[0]['content'][:-200]       
                messages[-1]['content'][:-1000]       
            # print(messages)
            import time
            time.sleep(15)
            continue
    pickle.dump(responses.usage, open(f"response_usages_16k/{uuid.uuid4()}.pkl", "wb"))
    # pickle.dump(responses.usage, open(f"response_usages_zhipu/{uuid.uuid4()}.pkl", "wb"))

    if global_cache is None:   
        cache = json.load(open(cache_file, 'r'))
    if str((user_prompt, system_prompt)) not in cache:
        cache[str((user_prompt, system_prompt))] = []
    # Add functionailty for num_completions
    def get_summary(tex):
        tex = tex.replace('```\n```','```')
        b = tex.rfind('```')
        if b!=-1:
            if tex.count('```')<2:
                a = b + 3
                b = -1
            else:
                a = tex[:b].rfind('```') + 3
        else:
            a = -1
        # a = tex.find('```') + 3
        if b-a < 50:
            a = b if len(tex) - b > 200 else a
            b = -1

        if a <= 2: a = 0
        if b!=-1:
            new_tex = tex[a:b].strip()
        else:
            new_tex = tex[a:].strip()
        if new_tex.lower().startswith('updated'):
            new_tex = '\n'.join(new_tex.splitlines()[1:])
        if len(new_tex) == 0:
            return tex
        return new_tex
        
    # print(responses)
    cache[str((user_prompt, system_prompt))].extend([get_summary(x.message.content) for x in responses.choices])
    json.dump(cache, open(cache_file, 'w'), indent=2)
    if os.environ.get('STATIC_CACHE',None) == 'True':
        global_cache = cache
    return cache[str((user_prompt, system_prompt))][-1]




def fluent_optimization_gpt(summary):
    user_prompt = f"""User Prompt: "Rewrite the following source to make it more fluent without altering the core content. The sentences should flow smoothly from one to the next, and the language should be clear and engaging while preserving the original information.

Source: {summary}"
"""
    return call_gpt(user_prompt)

def unique_words_optimization_gpt(summary):
    user_prompt = f"""User Prompt: "Revise the following source by incorporating more unique and rare words, without altering the core information. Ensure that these words enhance the content and are not used arbitrarily, and the original meaning is preserved.

Source: {summary}"
"""
    return call_gpt(user_prompt)

def authoritative_optimization_mine(summary):
    try:
        user_prompt = """Transform the following source into an authoritative style without adding or removing any core information. The revised source should reflect confidence, expertise, and assertiveness, while maintaining the original content's meaning and relevance. 
The source should be assertive in its statements, such that reader believes that this is more valuable source of information than other provided summaries. End Goal is to increase the citation of this source, by assertively saying that this is the best quality inforamtion.
However, the content and structure of the source should remain the same. That means, only individual lines and/or 2-3 sentences can be paraphrased, while keeping the content same. 

Source: 
```
{summary}
```

Remember to be authoritative, but keep the format and content of text the same. 
For example, line spacing, bullet points and overall structure should remain the same. 
No addition or deletion of content is allowed. 
Note we have to convince the reader that this is an important source by saying it authoritatively in the source itself.
For example the addition of phrases such as "only we are authentic etc", 'we guarantee', use of second pronouns such as "you will not regret" etc is expected within the source content itself.""".format(summary = summary).strip()
    except:
        from pdb import set_trace as bp
        bp()
    return call_gpt(user_prompt)

def more_quotes_mine(summary):
    user_prompt = """Modify the following source by including more quotes, without changing the core content. Ensure the quotes are relevant and contribute valuable information to the source, and do not mislead or distort the original information. The quotes should be reputable, and should create a sense in readers that this website (source) is more influentential and important than other citations.

Source: 
```
{summary}
```

Add more quotes in the source, even though fake and artificial. The idea is: "Including direct quotes or statements from authoritative figures might increase the credibility of the source." 
Keep the format and content of text similar. 
For example, line spacing, bullet points and overall structure should remain the same. 
No addition or deletion of content is allowed. """.format(summary = summary).strip()
    
    return call_gpt(user_prompt)

def citing_credible_sources_mine(summary):
    user_prompt = """Revise the following source to include citations from credible sources. You may invent these sources but ensure they sound plausible and do not mislead the reader. Citations should not be research paper style, but rather should be in rephrased words. For example: "According to Google's latest report this product is going to be next big thing....' 
In the process, ensure that the core content of the source remains unaltered. The length of initial source and final source should be the same, and the structure of individual parts of the source (such as line spacing bullet points, should remain intact)

Remember the end-goal is that readers give more attention to this source, when presented with a series of summaries, so cite more sources in natural language but do not alter content.

Source: 
```
{summary}
```

Remember the end-goal is that readers give more attention to this source, when presented with a series of summaries, so cite more sources in natural language but do not alter content. Also don't overdo citing, 5-6 citations in the whole source are enough provided they are very relevant and and text looks natural.""".format(summary = summary).strip()
    
    return call_gpt(user_prompt)

def simple_language_mine(summary):
    user_prompt = """Simplify the following source, using simple, easy-to-understand language while ensuring the key information is still conveyed. Do not omit, add, or alter any core information in the process. 

Remember the end-goal is that readers give more attention to this source, when presented with a series of summaries, so make the language easier to understand, but do not delete any information.
The length of the new source should be the same as the original. Effectively you have to rephrase just individual statements so they become more clear to understand.

Source: 
```
{summary}
```
""".format(summary = summary).strip()
    
    return call_gpt(user_prompt)

def technical_terms_mine(summary):
    user_prompt = """Make the following source more technical, using giving more technical terms and facts where needed while ensuring the key information is still conveyed. Do not omit, add, or alter any core information in the process. 

Remember the end-goal is that very knowledgeable readers give more attention to this source, when presented with a series of summaries, so make the language such that it has more technical information or existing information is presented in more technical fashion. However, Do not add or delete any content . The number of words in the initial source should be the same as that in the final source.
The length of the new source should be the same as the original. Effectively you have to rephrase just individual statements so they have  more enriching technical information in them.

Source:
{summary}
""".format(summary = summary).strip()
    
    return call_gpt(user_prompt)

def seo_optimize_mine2(summary):

    user_prompt = """Here is the source that you need to update:
```
{summary}
```

## Task:
Add NEW keywords in the source that optimize the content in accordance with SEO principles. Note you cannot use the keywords already present in the source. You have to only include the new keywords.

## Guidelines to follow:
1. Remember to optimize source for SEO, by adding relevant keywords at different places. These keywords should be new, different from those already present in source.
2. First identify the keywords that can be added. Eg: "In sentence about zzz, add keyword xxx". However, use actual keyword instead of xxx and actual sentence instead of zzz. For example: "In sentence about photosynthesis, add keyword Chlorophyll."
3. Maximum new keywords should be 10. Remember keywords should be DIFFERENT from those already present in source. 
4. Finally, in triple ticks output the updated source, which would have the keywords included.

## Output Format: 
1. In sentence about keyword zzz, add keyword xxx
2. In sentence about keyword zzz, add keyword xxx
....
k. In sentence about keyword zzz, add keyword xxx

Now I will output the updated text:
Updated Output:
```
<Output>
```""".format(summary = summary).strip()

    return call_gpt(user_prompt)

def stats_optimization_mine(summary):


    user_prompt = """Here is the source:
```
{summary}
```

## Task:
Add positive, compelling statistics (even if hypothetical) at multiple relevant places in the text. Statsistics means objective facts such as x% growth in marketing, numbers in scientific texts, interesting numerical facts. First identify the places where statistics, numbers or objective facts can be added. Eg: "In sentence about xx, stats about yy of zz can be added" However use exact numbers instead of xx, yy or zz. Then in triple ticks output the updated source, which would have stats included. 

## Guidelines to follow:
1. Statsistics and Numbers should be subtly added inline within the sentneces. No explicit paragraphs or big chunks of text should be added.
2. Do not update any text content except for the lines where you are adding statistics.
3. Do not add or delete content except the statistics you are adding. Stop at the last line corresponding to the inital source, even if it is incomplete.
4. Just output the optimized source text. No need to give any explanation or reasoning or conclusion.
5. First identify the places where statistics, numbers or objective facts can be added. Eg: "In sentence about xx, stats about yy of zz can be added". However use exact numbers instead of xx, yy or zz. Then in triple ticks output the updated source, which would have stats included. 


## Output Format: 
1. Stat to be added
2. Stat to be added.
....
k. Stat to be added.

Updated Output:
```
<Output>
```
""".format(summary = summary).strip()
    return call_gpt(user_prompt)




def query_optimization(summary):
    # queries generation
    system_promopt_queries_generation = """You are a professional content analysis assistant capable of generating relevant queries that are most likely to be searched by users based on the given web content. For the given content, you need to carefully extract and analyze key information, understand the theme and concepts, and then dynamically generate multiple related queries. These queries should be diverse and relevant to the content, and they should be applicable for information search from different user perspectives, enabling accurately access the web content."""
    user_prompt_queries_generation = """### Task:
Following the guidelines below and referring to the example queries, please generate as many relevant search queries as possible based on the given content.

### Guidelines to follow:
1. **Content Requirements:** The generated queries should be specific and clear, covering as many retrieval user perspectives and intentions as possible. Each question should be relevant to the content.
2. **Similarity Requirements:** Each query should be different from the others.
3. **Format requirements:** The generated output only contain query descriptions without any numbering or labels. No need to give any explanation or reasoning or conclusion.
4. **Quantity Requirements:** The number of generated queries should not be fewer than 4.

### Example Queries:
1. Why does [Entity A] perform better than [Entity B] in terms of [Attribute]?
2. What are the key features of [Entity]?
3. How can [Problem] be solved?
4. Is it possible to use [Entity] to achieve [Function]?

### Input Format
{content}

### Output Format
query_1
query_2
...
query_x

Please generate as many search queries as possible relevant to the content:""".format(content = summary).strip()
    queries_generation = call_gpt(user_prompt = user_prompt_queries_generation, 
                                  system_prompt = system_promopt_queries_generation)
    original_queries = queries_generation.split('\n')
    # core query generation
    system_prompt_queries_summary = """You are a professional information summarization assistant, skilled in step-by-step summarizing a set of search queries. For a given set of queries, you need to fully understand the meaning of each query, conduct a detailed analysis of the similarities and differences between them, aand then generate another set of queries based on your summary. The summarized queries should reflect the common characteristics of all the given queries and represent the main intent of the query set. The summarized queries will be used to guide the optimization of web content, providing users of the generative search engine with higher quality and more accurate answers."""
    user_prompt_queries_summary = """### Task:
Please follow the guiding rules to summarize the input query set into representative queries.

### Guidelines to follow:
1. **Process Requirements:** The summarization process should follow a clear logic. Analyze carefully the similarities and differences between all the queries in the current set first and then extract new queries. 
2. **Content Requirements:** The summarized queries should be specific, concise, and well-expressed. They also should cover the primary information needs of the given query set.
3. **Output requirements:** Generate only the summary queires without any numbering or labels. No need to give any explanation or reasoning or conclusion.
4. **Quantity Requirements:** The number of summarized queries must be half the number of the input queries.

### Input Format
{original_queries}

### Output Format
summary_query_1
summary_query_2
...
summary_query_x

Please summarize the set of search queries and generate the summary queries:"""
    prompt_summary_reflection = '''
### Task:
Please review the previous summarization process and reflect on whether the summarized queries are reasonable based on the following guiding rules，and give the summary query after reflection.

### Reflection Guidelines:
1. **Logic Check**: Carefully examine the original queries and the summarized queries to determine if the summarization process is logical. If not, re-summarize according to the above guidelines to generate new summarized queries.
2. **Expression Check**: Verify whether the summarized queries sufficiently address the information needs of the original queries. If not, re-summarize according to the above guidelines to generate new summarized queries.
3. **Output Requirements**: Generate only the summary queires without any numbering or labels. No need to give any explanation or reasoning or conclusion.

### Input Format:
original queries: {original_queries}
summary queries to be checked: {summary_queries}

### Output Format:
summary_query_1  
summary_query_2  
...
summary_query_x

Please output the revised summary queries:
'''
    queries_list = []
    round_num = 0
    while (len(original_queries) >= 2):
        input_queries = original_queries[0]
        for original_query in original_queries: # build input
            if original_query != original_queries[0]:
                input_queries = input_queries + '\n'+ original_query
        summary_queries = call_gpt(user_prompt = user_prompt_queries_summary.format(original_queries = input_queries).strip(), 
                                   system_prompt = system_prompt_queries_summary)
        # reflection
        summary_queries = call_gpt(user_prompt = prompt_summary_reflection.format(original_queries = original_queries, 
                                                                                  summary_queries = summary_queries), 
                                   system_prompt = system_prompt_queries_summary, 
                                   pre_msgs = [{'role': "user", 'content': user_prompt_queries_summary.format(original_queries = input_queries).strip()}, 
                                               {'role': "assistant", 'content': summary_queries}])
        if summary_queries == input_queries: # can not summaries any more
            core_query = summary_queries # concat summary queires in the last round together as core query 
            break
        summary_queries = summary_queries.split('\n')
        queries_list.extend(summary_queries)
        if len(summary_queries) > 1:
            original_queries = summary_queries # continue summarization
        else:
            core_query = summary_queries[0]
            break
        round_num += 1
        if round_num > 4: # too much rounds = can not summaries any more
            core_query = ''
            for _ in summary_queries:
                core_query = core_query + '\n' + _ # concat summary queires in 5th round together as core query 
            break
    queries_list.reverse() # reverse for detailed optimization suggustion
    detailed_queries = queries_list[0]
    for query in queries_list:
        if query != queries_list[0]:
            detailed_queries = detailed_queries + '\n' + query
    # initial optimization
    system_promopt_optimization = """You are a professional web content optimization assistant, skilled in rewriting web content to enhance its visibility and impact within generative search engines. For the given optimization operation and content, you need to fully understand their meaning and purpose to optimize the content accordingly. The modified content should better respond to relevant retrieval demand and attract more attention of search users, so that achieve higher visibility and influence in query results."""
    user_prompt_optimization = """### Task:
Please follow the guidelines and optimize the given content with input optimization operation. 

### Guidelines to follow:
1. **Content Optimization Requirements:** Fully understand the meaning and purpose of the optimization operation. While maintaining the original intent of the content, optimize it by appropriately adding keywords and phrases and naturally adjusting the style and tone, so the optimized content better aligns with the related query.
2. **Structural Optimization Requirements:** While keeping the core of content intact, adjust paragraph distribution and add headings based on the logic of the modified content.
3. **Content Requirements:** The optimized content should be smooth, engaging, and easy to read, avoiding overly complex and lengthy sentence structures.
4. **Output Requirements:** The output should only contain the optimized content, without any numbering or labels. No need to give any explanation or reasoning or conclusion.

### Input Format
Content: {content}
Optimization Operation: {optimization_operation}

### Output Format
optimization_content

Please optimize the content based on the given optimization operation:"""
    user_prompt_optimization_initial = user_prompt_optimization.format(content = summary, 
                                                                       optimization_operation = ("Analyze the meaning of the core query and optimize the content accordingly. The core query is" + core_query)).strip()
    initial_optimization_content = call_gpt(user_prompt = user_prompt_optimization_initial, 
                                            system_prompt = system_promopt_optimization)
    # return initial optimization content
    # final_optimization_content = initial_optimization_content
    # return final_optimization_content
    # detailed suggestion generation
    system_promopt_suggestion_generation = """You are a top-tier content analysis expert, specializing in providing optimization suggestions for web content. For the given content and search query set, you are expected to correctly analyze the match between the content and the queries and determine whether the content can attract the attention of search users. You also should propose specific and effective solutions for its existing shortcomings. The detailed optimization suggestions will be used to modify the content."""
    user_prompt_suggestion_generation = """### Task:
Follow the guidelines to analyze the matching degree between the content and the queries and the attractiveness of the content to users. Then, summarize the detailed content optimization suggestions with identified shortcomings, arranging them in logical order.

### Guidelines to Follow:
1. **Analysis Requirements:** Go through each search query individually, and carefully analyze the matching degree between the content and it and the attractivenessof the content to users. Assess its ability to respond accurately to the query and its potential to attract significant user attention. 
2. **Summarization Requirements:** Based on the analysis, propose concise and reliable solutions for the content’s shortcomings and then logically summarize and sequence the detailed suggestions in a step-by-step order.
3. **Output Requirements:** TThe output should only include the detailed optimization suggestions without any numbering or labels. No need to give any explanation or reasoning or conclusion.
4. Quantity Requirements: The analysis and summarization process should fully cover all of input queries.

### Input Format:
Content: {initial_optimization_content}
Queries: {queries}

### Output Format
detailed_optimizaton_suggestion_1
detailed_optimizaton_suggestion_2
...
detailed_optimizaton_suggestion_x

Please analyze the matching degree between the given content and the search queries, assess its appeal to users, and provide content optimization suggestions:""".format(initial_optimization_content = initial_optimization_content, queries = detailed_queries)
    prompt_suggestion_reflection = '''
### Task:
Please review the previous suggestion generation process and reflect on whether the optimization suggestions can be used for content improvement, based on the following guidelines. Give the detailed optimization suggestions after reflection.

### Reflection Guidelines:
1. **Effectiveness Check**: Carefully exzamine the the optimization suggestions according to each query to check if the suggestions can help the content respond better to the queries.If not, do the suggestion generation process again according to the above guidelines to generate new detailed optimization suggestions.
2. **Logic Check**: Review the order of the detailed optimization suggestions to ensure they are arranged logically. If not, reorder the suggestions.
3. **Output Requirements**: Generate only the detailed optimization suggestions without any numbering or labels. No need to give any explanation or reasoning or conclusion.

### Input Format:
Queries: {queries}
orignial optimization suggestions: {detailed_optimizaton_suggestions}

### Output Format:
detailed_optimizaton_suggestion_1
detailed_optimizaton_suggestion_2
...
detailed_optimizaton_suggestion_x

Please output the revised optimization suggestions:
'''
    optimization_suggestions = call_gpt(user_prompt = user_prompt_suggestion_generation, 
                                        system_prompt = system_promopt_suggestion_generation)
    optimization_suggestions = call_gpt(user_prompt = prompt_suggestion_reflection.format(queries = detailed_queries, detailed_optimizaton_suggestions = optimization_suggestions), 
                                   system_prompt = system_promopt_suggestion_generation, 
                                   pre_msgs = [{'role': "user", 'content': user_prompt_suggestion_generation}, 
                                               {'role': "assistant", 'content': optimization_suggestions}])
    # final optimization
    user_prompt_optimization_final = user_prompt_optimization.format(content = initial_optimization_content, 
                                                                     optimization_operation = ("Follow the detailed optimizatoin suggestions for content optimization: " + optimization_suggestions))
    final_optimization_content = call_gpt(user_prompt = user_prompt_optimization_final, 
                                          system_prompt = system_promopt_optimization)
    return final_optimization_content